[nodes]
rtr-a: _ radius=1 angle=1.0 cache=1000
rtr-a1: _ radius=0.5 angle=1.1 cache=1000
rtr-a1a: _ radius=0.25 angle=1.2 cache=0
rtr-a2: _ radius=0.5 angle=1.3 cache=1000
rtr-a2a: _ radius=0.25 angle=1.4 cache=0
rtr-b: _ radius=1 angle=1.5 cache=1000
rtr-b1: _ radius=0.5 angle=1.6 cache=1000
rtr-b1a: _ radius=0.25 angle=1.7 cache=0
rtr-c: _ radius=1 angle=1.8 cache=1000
rtr-c1: _ radius=0.5 angle=1.9 cache=1000
rtr-c1a: _ radius=0.25 angle=1.10 cache=0
rtr-c1b: _ radius=0.25 angle=1.11 cache=0
rtr-d: _ radius=1 angle=1.12 cache=1000
rtr-d1: _ radius=0.5 angle=1.13 cache=1000
rtr-d2: _ radius=0.5 angle=1.14 cache=1000
rtr-e: _ radius=1 angle=1.15 cache=1000
rtr-e1: _ radius=0.5 angle=1.16 cache=1000
rtr-e1a: _ radius=0.25 angle=1.17 cache=0
rtr-f: _ radius=1 angle=1.18 cache=1000
rtr-f1: _ radius=0.5 angle=1.19 cache=1000
rtr-f2: _ radius=0.5 angle=1.20 cache=1000
rtr-f2a: _ radius=0.25 angle=1.21 cache=0
rtr-g: _ radius=1 angle=1.22 cache=1000
rtr-g1: _ radius=0.5 angle=1.29 cache=1000
rtr-g1a: _ radius=0.25 angle=1.30 cache=0
rtr-g1b: _ radius=0.25 angle=1.31 cache=0
rtr-h: _ radius=1 angle=1.23 cache=1000
rtr-h1: _ radius=0.5 angle=1.24 cache=1000
rtr-h1a: _ radius=0.25 angle=1.25 cache=0
rtr-i: _ radius=1 angle=1.26 cache=1000
rtr-i1: _ radius=0.5 angle=1.32 cache=1000
rtr-i1a: _ radius=0.25 angle=1.33 cache=0
rtr-i1b: _ radius=0.25 angle=1.34 cache=0
rtr-i2: _ radius=0.5 angle=1.35 cache=1000
rtr-i2a: _ radius=0.25 angle=1.36 cache=0
rtr-i2b: _ radius=0.25 angle=1.37 cache=0
rtr-j: _ radius=1 angle=1.27 cache=1000
rtr-j1: _ radius=0.5 angle=1.41 cache=1000
rtr-j1a: _ radius=0.25 angle=1.42 cache=0
rtr-k: _ radius=1 angle=1.28 cache=1000
rtr-k1: _ radius=0.5 angle=1.38 cache=1000
rtr-k1a: _ radius=0.25 angle=1.39 cache=0
rtr-k1b: _ radius=0.25 angle=1.40 cache=0

[links]
rtr-a:rtr-b delay=5ms bw=100
rtr-a:rtr-c delay=5ms bw=100
rtr-b:rtr-c delay=5ms bw=100
rtr-c:rtr-e delay=5ms bw=100
rtr-e:rtr-g delay=5ms bw=100
rtr-g:rtr-i delay=5ms bw=100
rtr-i:rtr-k delay=5ms bw=100
rtr-k:rtr-j delay=5ms bw=100
rtr-j:rtr-h delay=5ms bw=100
rtr-h:rtr-f delay=5ms bw=100
rtr-f:rtr-d delay=5ms bw=100
rtr-d:rtr-b delay=5ms bw=100
rtr-e:rtr-f delay=5ms bw=100
rtr-g:rtr-j delay=5ms bw=100

rtr-a:rtr-a1 delay=2ms bw=10
rtr-a:rtr-a2 delay=2ms bw=10
rtr-c:rtr-c1 delay=2ms bw=10
rtr-e:rtr-e1 delay=2ms bw=10
rtr-h:rtr-h1 delay=2ms bw=10
rtr-f:rtr-f1 delay=2ms bw=10
rtr-f:rtr-f2 delay=2ms bw=10
rtr-d:rtr-d1 delay=2ms bw=10
rtr-d:rtr-d2 delay=2ms bw=10
rtr-b:rtr-b1 delay=2ms bw=10
rtr-g:rtr-g1 delay=2ms bw=10
rtr-i:rtr-i1 delay=2ms bw=10
rtr-i:rtr-i2 delay=2ms bw=10
rtr-k:rtr-k1 delay=2ms bw=10
rtr-j:rtr-j1 delay=2ms bw=10

rtr-a1:rtr-a1a delay=1ms bw=1
rtr-a2:rtr-a2a delay=1ms bw=1
rtr-c1:rtr-c1a delay=1ms bw=1
rtr-c1:rtr-c1b delay=1ms bw=1
rtr-e1:rtr-e1a delay=1ms bw=1
rtr-h1:rtr-h1a delay=1ms bw=1
rtr-f2:rtr-f2a delay=1ms bw=1
rtr-b1:rtr-b1a delay=1ms bw=1
rtr-g1:rtr-g1a delay=1ms bw=1
rtr-g1:rtr-g1b delay=1ms bw=1
rtr-i1:rtr-i1a delay=1ms bw=1
rtr-i1:rtr-i1b delay=1ms bw=1
rtr-i2:rtr-i2a delay=1ms bw=1
rtr-i2:rtr-i2b delay=1ms bw=1
rtr-k1:rtr-k1a delay=1ms bw=1
rtr-k1:rtr-k1b delay=1ms bw=1
rtr-j1:rtr-j1a delay=1ms bw=1
